name: java based workflow
on:
 workflow_dispatch:
jobs:
 echo-triggers:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v1
   - name: javasetup  
     uses: actions/setup-java@v4.6.0
     with:
       distribution: 'microsoft'
       java-version: '17'
   - run: mvn --batch-mode --update-snapshots verify
   - run: mkdir staging && cp target/*.jar staging
   - uses: actions/upload-artifact@v4.5.0
     with:
      name: Package
      path: staging
      
      
     
